meta_product_name: "Climbly"
meta_title: "Climbly - Discover Mauritius and Challenge yourself with your friends through Hiking."
meta_description: "Discover Mauritius and Challenge yourself with your friends through Hiking."
meta_image: "https://res.cloudinary.com/deqc25xt2/image/upload/v1655271787/development/image-banner-meta_nunsio.jpg" # should exist in `app/assets/images/`
